project:
  type: website
  output-dir: docs

website:
  title: "5805 Machine Learning Blog"
  navbar:
    right:
      - about.qmd
      - icon: house
        text: Home
        href: https://greg808b.github.io
      - icon: linkedin
        text: LinkedIn
        href: https://linkedin.com/in/greg808b
      - icon: github
        text: Github
        href: https://github.com/greg808b
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

