project:
  type: website
  output-dir: docs

website:
  title: "5805 Machine Learning Blog"
  navbar:
    right:
      - icon: person-circle 
        href: /about.html
      - icon: house
        href: https://greg808b.github.io
      - icon: linkedin
        href: https://linkedin.com/in/greg808b
      - icon: github
        href: https://github.com/greg808b
format:
  html:
    theme: plain
    css: styles.css

editor: visual

